indication_paths.yaml
=> Updated issues 1 and 3

indication_paths.yaml
added issue 4 and made corrections to issue 1 and 3
=> added issue 4 and made corrections to issue 1 and 3

indication_paths.yaml
Following @mmayers12 feedback, most of entries in group 2 are now correctly (hopefully) captured here. :)
=> Updated indication_paths.yaml w/ group 2

indication_paths.yaml
=> Update indications_path.yaml group_0 completed

indication_paths.yaml
=> added issue 7

indication_paths.yaml
=> corrections to bacteria

indication_paths.yaml
=> added issue 8 and 11

indication_paths.yaml
@mmayers12, there was a set of complicated paths outstanding from group 2.
These new entries should do the job for that group now, so that issue #12 can be closed.
In addition, I also include 1/2 of entries from group 10.
=> Missing group 2 + half of group 10

indication_paths.yaml
=> updates issues 13 and 14

indication_paths.yaml
These are all drugs from group 16 with the exception of lactose and iloprost, which are currently under review.
=> Update .yaml with Group 16 minus 2 drugs

indication_paths.yaml
Updated Recurated-batch(6 and 12)-Curated batch 17
=> Recurated-batch(6,12)-Curated batch 17

indication_paths.yaml
File now updated to contain entries from group 18 plus some outstanding terms from groups 10 and 16.
=> paths.yaml updated with group 18 and more

submission.yaml
curated batch 24_all path visualization checked
=> curated batch 24

submission.yaml
=> One more correction test

CurationGuide.md
"the different diseases" --> "different diseases"
=> Fixing a minor typo

submission.yaml
=> Group_85_curated

submission.yaml
If all is well, issue  #331 can be closed.
=> Group 105 is now complete

submission.yaml
Improvements/amendments on
- ergotamine paths
- hypertensive disorder-hydroflumethiazide path
- azosemide-CHF
=> Group 110 w/ improvements

submission.yaml
For more details, see original PR #379 .
=> Group 118 now amended

submission.yaml
New submission taking into account suggestions from @TanskaAnnna. 
For the entire history check previous PR (#418).
=> Group 133 w/ adjustments

submission.yaml
=> Group 9 re-curation

submission.yaml
DB00758_MESH_D054058_1 (Clopidogrel - Acute Coronary Syndrome) DB00758_MESH_D020766_1 (Clopidogrel - Intracranial Embolism)
=> Clopidogrel drug re-curation from group 6

submission.yaml
=> Group 12 re-curation

submission.yaml
=> Two paths from group 17

submission.yaml
=> Group 17 re-curation

submission.yaml
Acebutolol _ Hypertension from group 20 (Drug without path ID)
=> Acebutolol _ Hypertension from group 20

submission.yaml
=> Group 20 re-curation

submission.yaml
Group 29 re-curation submission
=> Group 29 re-curation submission

submission.yaml
Group 36 re-curation submission
=> Group 36 re-curation submission

submission.yaml
Group 47 re-curation submission
=> Group 47 re-curation submission

submission.yaml
Group 49 re-curation submission
=> Group 49 re-curation submission

submission.yaml
Group58 re-curation submission
=> Group58 re-curation submission

submission.yaml
Group 63 re-curation submission
=> Group 63 re-curation submission

submission.yaml
Group 66 re-curation submission
=> Group 66 re-curation submission
